#!/usr/bin/env sh

 ##################
## System Tool(s) ##
 ##################
alias src='. $HOME/.bashrc'
alias ssh='ssh -X'
# TODO: Figure out how to make this always open the default text editor.
alias txtEdit='xdg-open'

 #######################
## Development Tool(s) ##
 #######################
## Git Setup ##
export GIT_ROOT=$HOME/git

 ##################
## Combination(s) ##
 ##################
## Environment Config ##
# Clear, show current, location, and location's content(s).
alias c='clear;pwd;ls -a'
# Same as 'c' pluse git status and branch.
alias g='c;git status;git branch -a'
# Git fetch.
alias gF='git fetch --all -ftp'

