#!/usr/bin/env sh

 ######################
## Path Short Hand(s) ##
 ######################
# Shell root.
if [[ -d "$HOME/shell" ]]; then
	declare -x SHELL_ROOT=$HOME/shell
else
	# Attempt to find shell root in bash.
	if [[ -d "${BASH_SOURCE%/*}" ]]; then
		declare -x SHELL_ROOT=${BASH_SOURCE%/*}
	else
		echo "Failed to find root of shell scripts."
	fi
fi
echo "SHELL_ROOT: '$SHELL_ROOT'"
# Shell function(s) root.
declare -x SHELL_FUNCTIONS=$SHELL_ROOT/functions
echo "SHELL_FUNCTIONS: '$SHELL_FUNCTIONS'"
# Shell function's constant(s).
declare -x SHELL_FUNCTIONS_CONSTANTS=$SHELL_FUNCTIONS/constants
echo "SHELL_FUNCTIONS_CONSTANTS: '$SHELL_FUNCTIONS_CONSTANTS'"

 ###########################
## Global Function(s)/Data ##
 ###########################
## Data ##
# Includes variables relevant to all functions.
. $SHELL_FUNCTIONS/variablesGlobal.sh

## Function(s) ##
# Include output producing/formatting function(s) used by other function(s) in the same/child directories.
#   Note: If location/name of this file changes, update all other *.sh files in the same directory.
alias output=$SHELL_FUNCTIONS/output.sh
# Include shell option checking function used by other function(s) in the same/child directories.
alias checkRequiredOpts=$SHELL_FUNCTIONS/checkRequiredOpts.sh
# Include log function used by other function(s) in the same/child directories.
function log() {
	$SHELL_FUNCTIONS/log.sh "${@}"
}
export -f log
# Include function that backs up local home directory to "external" drive.
alias backUp=$SHELL_FUNCTIONS/backUp.sh

