name: Install shellspec
description: Installs shellspec (testing tool) onto runner.
runs:
  using: 'composite'
  steps:
    - name:  Installing 'shellspec' (POSIX shell script testing tool)...
      id:    shellspecInstall
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
    # shellspec's server doesn't reliably work, so retry when it fails.
    - name:  Installing 'shellspec' (retry 1)...
      id:    shellspecInstallRetry1
      if:    steps.shellspecInstall.outcome == 'failure'
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
    - name:  Installing 'shellspec' (retry 2)...
      id:    shellspecInstallRetry2
      if:    steps.shellspecInstallRetry1.outcome == 'failure'
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
    - name:  Installing 'shellspec' (retry 3)...
      id:    shellspecInstallRetry3
      if:    steps.shellspecInstallRetry2.outcome == 'failure'
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
    - name:  Installing 'shellspec' (retry 4)...
      id:    shellspecInstallRetry4
      if:    steps.shellspecInstallRetry3.outcome == 'failure'
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
    - name:  Installing 'shellspec' (retry 5)...
#      id:    shellspecInstallRetry5
      if:    steps.shellspecInstallRetry4.outcome == 'failure'
#      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes


#    - name: Installing 'shellspec' (POSIX shell script testing tool)...
#      uses: nick-fields/retry@v2.8.3
#      with:
#        max_attempts: 5
#        retry_on: error
#        timeout_seconds: 10
#        shell: bash
#        command: curl -fsSL https://git.io/shellspec | sh -s -- --yes

