name: Install shellspec
description: Installs shellspec (testing tool) onto runner.
runs:
  using: 'composite'
  steps:
    - name:  Installing 'shellspec' (POSIX shell script testing tool)...
      id:    shellspecInstall
      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes
	# shellspec's server doesn't reliably work, so retry when it fails.
    - name:  Installing 'shellspec' (retry)...
#      id:    shellspecInstallRetry
      if: steps.shellspecInstall.outcome == 'failure'
#      continue-on-error: true
      shell: bash
      run:   curl -fsSL https://git.io/shellspec | sh -s -- --yes

