name: Install shellspec
description: Installs shellspec (testing tool) onto runner.
runs:
  using: 'composite'
  steps:
    - name: Installing 'shellspec' (POSIX shell script testing tool)...
      uses: nick-fields/retry@v2.8.3
      with:
        max_attempts: 5
        retry_on: error
        timeout_seconds: 10
        shell: bash
        command: curl -fsSL https://git.io/shellspec | sh -s -- --yes

