name: Style Guide Check of verifyInputProvided()
run-name: ${{ github.actor }} has triggered style guide check of verifyInputProvided() for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}
on: [push, workflow_dispatch]
jobs:
  style-guide-verifyInputProvided:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Install Style Guide Checking Tool...
        uses: ./.github/actions/install-shfmt-via-snap
      - name: Running style guide check...
        run:  shfmt --diff --case-indent --posix ./src/shell/functions/util/verifyInputProvided.sh

