name: Unit Tests of output
run-name: ${{ github.actor }} is unit testing POSIX script output
on: [push, pull_request]
jobs:
  unit-test-output:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Checking out branch '${{ github.ref }}' from '${{ github.repository }}' repo on '${{ runner.os }}'..."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: echo '$PWD'
      - run: ls -GApl
      - name: Run unit tests
        run: ./tests/unit/bash_unit -f tap -p test_output__single_line__lower_alpha__single_char ./tests/unit/tests/output/test_output-required_options.sh

